apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-log
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - nodePort: 31000
      port: 8000
      targetPort: 5601
  selector:
    app: kibana
